spring:
  application:
    name: airport-management
  datasource:
    hikari:
      connection-timeout: 30000
    url: jdbc:postgresql://localhost:5433/airport
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none        
    show-sql: true              
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ── Flyway (migrations do PostgreSQL) ───────────────────────
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/airport
    user: postgres
    password: postgres
    locations: classpath:db/migration
    baseline-on-migrate: true
    repair-on-migrate: true

  # ── Cassandra ───────────────────────────────────────────────
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: airport_logs
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS   

  # ── Redis ───────────────────────────────────────────────────
  data:
    redis:
      host: localhost
      port: 6379

# ── Porta da API ────────────────────────────────────────────
server:
  port: 8080
