spring:
  datasource:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 3000
      initialization-fail-timeout: 0
    url: jdbc:postgresql://localhost:5433/airport
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5433/airport
    user: postgres
    password: postgres
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: airport_logs
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
    request:
      timeout: 10s
    connection:
      connection-timeout: 15s
      init-query-timeout: 15s
  data:
    redis:
      host: localhost
      port: 6379