ALTER TABLE aeroporto ALTER COLUMN iata TYPE VARCHAR(3);
ALTER TABLE aeroporto ALTER COLUMN uf TYPE VARCHAR(2);
ALTER TABLE voo ALTER COLUMN origem TYPE VARCHAR(3);
ALTER TABLE voo ALTER COLUMN destino TYPE VARCHAR(3);
ALTER TABLE passageiro ALTER COLUMN cpf TYPE VARCHAR(11);
